### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Wikunia** [peterflynn/anti-lint-js#1]
I would like to use your extension but don't know how to use it. Maybe you can add some more information to the readme. Do I need to change the brackets settings file?

```
{
    "jslint.options": {
        "vars": true,
        "plusplus": true,
        "devel": true,
        "nomen": true,
        "maxerr": 50,
        "es5": true
    },
    "defaultExtension": "js",
    "path": {
        "src/thirdparty/CodeMirror2/**/*.js": {
            "spaceUnits": 2,
            "linting.enabled": false
        },
        "src/thirdparty/globmatch.js": {
            "spaceUnits": 2,
            "linting.enabled": false
        }
    },
    "spaceUnits": 4,
    "useTabChar": false
}
```

**Comment by peterflynn** [comment]
@Wikunia The syntax checker runs automatically whenever you save or open a JS file, just like the default JSLint checker that Brackets comes with.  No preferences changes are needed.  Are you having trouble getting it to work?

**Comment by Wikunia** [comment]
I changed the linter some time ago because I didn't like it and hopefully I love yours :) Is there a panel where I should see errors? Maybe you can add some screenshots or sth like that and I'll have a look tomorrow. Have a nice weekend!

**Comment by peterflynn** [comment]
Make sure _File > Lint Files on Save_ is enabled?

**Comment by Wikunia** [comment]
It's `View-> Lint Files on Save` and yes that was the problem :) Thanks!
